# Generated by Django 6.0.1 on 2026-01-30 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_dementiaassessment_delete_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dementiaassessment',
            name='risk_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dementiaassessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
