# Generated by Django 6.0.1 on 2026-01-30 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_dementiaassessment_risk_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognitive_done', models.BooleanField(default=False)),
                ('voice_done', models.BooleanField(default=False)),
                ('questionnaire_done', models.BooleanField(default=False)),
                ('cognitive_score', models.FloatField(blank=True, null=True)),
                ('voice_score', models.FloatField(blank=True, null=True)),
                ('questionnaire_score', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
