# Generated by Django 6.0.1 on 2026-02-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_teststatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teststatus',
            old_name='cognitive_done',
            new_name='attention_done',
        ),
        migrations.RenameField(
            model_name='teststatus',
            old_name='cognitive_score',
            new_name='attention_score',
        ),
        migrations.AddField(
            model_name='teststatus',
            name='memory_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teststatus',
            name='memory_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
