# Generated by Django 6.0.1 on 2026-02-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_rename_cognitive_done_teststatus_attention_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststatus',
            name='digit_span_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teststatus',
            name='digit_span_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teststatus',
            name='trail_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teststatus',
            name='trail_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
